-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.runes
(
    rune_id character varying(16) COLLATE pg_catalog."default" NOT NULL,
    spaced_rune character varying(64) COLLATE pg_catalog."default" NOT NULL,
    number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    divisibility smallint DEFAULT 0 NOT NULL,
    symbol character varying(4),
    etching character varying(64) COLLATE pg_catalog."default" NOT NULL,
    mint_deadline bigint,
    mint_end bigint,
    mint_limit character varying(39) COLLATE pg_catalog."default",
    mints character varying(20) COLLATE pg_catalog."default" NOT NULL,
    burned character varying(39) COLLATE pg_catalog."default" NOT NULL,
    supply character varying(39) COLLATE pg_catalog."default" NOT NULL,
    timestamp timestamp with time zone NOT NULL,
    CONSTRAINT runes_pkey PRIMARY KEY (rune_id)
);

CREATE TABLE IF NOT EXISTS public.rune_balances
(
    rune_id character varying(16) COLLATE pg_catalog."default" NOT NULL,
    address character varying(64) COLLATE pg_catalog."default" NOT NULL,
    amount character varying(39) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT rune_balances_pkey PRIMARY KEY (rune_id, address)
);

CREATE TABLE IF NOT EXISTS public.rs_transactions
(
    tx_id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    transaction json,
    CONSTRAINT rs_transactions_pkey PRIMARY KEY (tx_id)
);

ALTER TABLE IF EXISTS public.rune_balances
    ADD FOREIGN KEY (rune_id)
    REFERENCES public.runes (rune_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;